// ---------------------------------------------------------------------------
// mockTemplates.js — Realistic mock template data for the onboarding gallery.
// In production, this data comes from GET /api/templates.
// ---------------------------------------------------------------------------

const DEFAULT_COLOR_SCHEMES = [
  { name: 'Default', primary: '#8B3DFF', secondary: '#F0E8FF' },
  { name: 'Vibrant', primary: '#FF3366', secondary: '#FFE5EC' },
  { name: 'Ocean',   primary: '#00C4CC', secondary: '#E0FAFB' },
  { name: 'Dark',    primary: '#1A1D23', secondary: '#2D313A' },
];

const DEFAULT_FONT_OPTIONS = [
  { name: 'Modern Sans', value: "'Inter', sans-serif" },
  { name: 'Elegant Serif', value: "'Playfair Display', serif" },
  { name: 'Playful', value: "'Comic Sans MS', cursive" },
  { name: 'Monospace', value: "'JetBrains Mono', monospace" },
];

// Complete Store content — shared by all templates via spread
export const BASE_DEFAULT_CONTENT = {
  storeName: 'VIMI LUXE',
  heroTitle: 'Elevate Your Everyday.',
  heroSubtitle: 'Discover our curated collection of premium essentials designed for modern living. Crafted with intention and sustainable materials.',
  heroCta: 'Shop Collection',
  heroBg: 'https://picsum.photos/seed/complete-hero/1600/900',
  catTitle: 'Featured Categories',
  cat1Img: 'https://picsum.photos/seed/cat1/600/800',
  cat1Name: 'Modern Furniture',
  cat2Img: 'https://picsum.photos/seed/cat2/600/800',
  cat2Name: 'Lighting & Decor',
  cat3Img: 'https://picsum.photos/seed/cat3/600/800',
  cat3Name: 'Textiles & Rugs',
  topSellTitle: 'Best Sellers',
  prod1Img: 'https://picsum.photos/seed/prod1/500/500', prod1Name: 'Lounge Chair', prod1Price: '$499',
  prod2Img: 'https://picsum.photos/seed/prod2/500/500', prod2Name: 'Ceramic Vase', prod2Price: '$48',
  prod3Img: 'https://picsum.photos/seed/prod3/500/500', prod3Name: 'Table Lamp', prod3Price: '$125',
  prod4Img: 'https://picsum.photos/seed/prod4/500/500', prod4Name: 'Linen Throw', prod4Price: '$89',
  promoBg: 'https://picsum.photos/seed/promo/1400/600',
  promoTitle: 'Mid-Season Sale',
  promoSub: 'Up to 40% off selected lifestyle pieces. Refresh your space for the new season.',
  promoCta: 'Shop Further Reductions',
  newTitle: 'New Arrivals',
  testTitle: 'What our customers say',
  test1Quote: '"The quality of these pieces completely transformed my living room!"', test1Author: 'Sarah J.',
  test2Quote: '"Fast shipping and incredibly helpful customer support."', test2Author: 'Michael P.',
  test3Quote: '"I keep coming back for all my home decor needs."', test3Author: 'Emily R.',
  newsTitle: 'Join the club',
  newsSub: 'Sign up for our newsletter and get 10% off your first order.',
  footerDesc: 'Curating the world\u2019s most beautiful lifestyle goods since 2026. Designed with purpose.',
};

export const MOCK_TEMPLATES = [
  // ─── 1. Complete Store (Flagship) ─────────────────────────────────────────
  {
    id: 'tmpl_complete_store',
    name: 'Complete Store',
    category: 'E-commerce',
    primaryColor: '#1A1D23',
    accentColor: '#F8F9FA',
    defaultFont: "'Inter', sans-serif",
    heroLayout: 'fullwidth',
    layoutStyle: 'grid',
    borderRadius: 'none',
    colorSchemes: [...DEFAULT_COLOR_SCHEMES],
    fontOptions: [...DEFAULT_FONT_OPTIONS],
    defaultContent: { ...BASE_DEFAULT_CONTENT },
    description: 'A fully-featured, responsive e-commerce template with robust grid sections and native components built in.',
    tags: ['Complete', 'Grid', 'Store'],
    popular: true,
    isNew: true,
    featured: true,
  },

  // ─── 2. Minimal White ─────────────────────────────────────────────────────
  {
    id: 'tmpl_minimal_white',
    name: 'Minimal White',
    category: 'General',
    primaryColor: '#8B3DFF',
    accentColor: '#F0E8FF',
    defaultFont: "'Inter', sans-serif",
    heroLayout: 'split',
    layoutStyle: 'grid',
    borderRadius: 'small',
    colorSchemes: [...DEFAULT_COLOR_SCHEMES],
    fontOptions: [...DEFAULT_FONT_OPTIONS],
    defaultContent: {
      ...BASE_DEFAULT_CONTENT,
      storeName: 'BLANC',
      heroTitle: 'Less Is More.',
      heroSubtitle: 'Beautifully simple products for a distraction-free life.',
      heroCta: 'Explore',
      heroBg: 'https://picsum.photos/seed/minimal-hero/1600/900',
      catTitle: 'Collections',
      cat1Name: 'Essentials', cat2Name: 'Workspace', cat3Name: 'Wellness',
      topSellTitle: 'Fan Favourites',
      promoTitle: 'Clean Living Sale',
      promoCta: 'Shop Now',
      newsTitle: 'Stay in the Loop',
      footerDesc: 'Thoughtfully crafted for modern minimalists.',
    },
    description: 'A clean, distraction-free layout that puts your products front and center. Perfect for premium brands.',
    tags: ['Minimal', 'Clean', 'Premium'],
    popular: true,
    isNew: false,
    featured: true,
  },

  // ─── 3. Fashion Forward ───────────────────────────────────────────────────
  {
    id: 'tmpl_fashion_forward',
    name: 'Fashion Forward',
    category: 'Fashion',
    primaryColor: '#FF6B9D',
    accentColor: '#FFF0F6',
    defaultFont: "'Playfair Display', serif",
    heroLayout: 'centered',
    layoutStyle: 'masonry',
    borderRadius: 'large',
    colorSchemes: [...DEFAULT_COLOR_SCHEMES],
    fontOptions: [...DEFAULT_FONT_OPTIONS],
    defaultContent: {
      ...BASE_DEFAULT_CONTENT,
      storeName: 'LUMIÈRE',
      heroTitle: 'Dare to be Different.',
      heroSubtitle: 'Bold editorial fashion for the unapologetically individual.',
      heroCta: 'Explore Lookbook',
      heroBg: 'https://picsum.photos/seed/fashion-hero/1600/900',
      catTitle: 'Shop by Look',
      cat1Name: 'Statement Pieces', cat2Name: 'Street to Chic', cat3Name: 'Evening Wear',
      topSellTitle: 'Editor\'s Picks',
      promoTitle: 'Season\'s Must-Haves',
      promoCta: 'Shop the Drop',
      newsTitle: 'Be the First to Know',
      footerDesc: 'Fashion-forward since day one.',
    },
    description: 'Bold editorial layouts, oversized imagery, and stunning lookbook-style product displays.',
    tags: ['Bold', 'Editorial', 'Trendy'],
    popular: true,
    isNew: false,
    featured: true,
  },

  // ─── 4. Nike Dynamic ─────────────────────────────────────────────────────
  {
    id: 'tmpl_nike_dynamic',
    name: 'Nike Dynamic',
    category: 'Sports',
    primaryColor: '#FF5733',
    accentColor: '#FFF2EF',
    defaultFont: "'Inter', sans-serif",
    heroLayout: 'fullwidth',
    layoutStyle: 'grid',
    borderRadius: 'none',
    colorSchemes: [...DEFAULT_COLOR_SCHEMES],
    fontOptions: [...DEFAULT_FONT_OPTIONS],
    defaultContent: {
      ...BASE_DEFAULT_CONTENT,
      storeName: 'DYNA',
      heroTitle: 'JUST DO IT.',
      heroSubtitle: 'Performance footwear and activewear built to push limits.',
      heroCta: 'Shop Performance',
      heroBg: 'https://picsum.photos/seed/nike-hero/1600/900',
      catTitle: 'Shop by Sport',
      cat1Name: 'Running', cat2Name: 'Training', cat3Name: 'Basketball',
      topSellTitle: 'Top Performers',
      prod1Name: 'Air Max Pro', prod1Price: '$189',
      prod2Name: 'Compression Tee', prod2Price: '$45',
      prod3Name: 'Speed Shorts', prod3Price: '$65',
      prod4Name: 'Trail Runner', prod4Price: '$159',
      promoTitle: 'Limited Edition Drop',
      promoCta: 'Get Yours',
      newsTitle: 'Join the Squad',
      footerDesc: 'Empowering athletes everywhere.',
    },
    description: 'High-energy layouts with bold typography and dynamic grid systems for sports and activewear.',
    tags: ['Bold', 'Dynamic', 'Sports'],
    popular: true,
    isNew: true,
    featured: true,
  },

  // ─── 5. Tech Gadgets ─────────────────────────────────────────────────────
  {
    id: 'tmpl_tech_gadgets',
    name: 'Tech Gadgets',
    category: 'Electronics',
    primaryColor: '#3B82F6',
    accentColor: '#0F172A',
    defaultFont: "'Inter', sans-serif",
    heroLayout: 'split',
    layoutStyle: 'grid',
    borderRadius: 'small',
    colorSchemes: [...DEFAULT_COLOR_SCHEMES],
    fontOptions: [...DEFAULT_FONT_OPTIONS],
    defaultContent: {
      ...BASE_DEFAULT_CONTENT,
      storeName: 'NEXUS',
      heroTitle: 'The Future, Delivered.',
      heroSubtitle: 'Cutting-edge electronics and smart devices for the connected lifestyle.',
      heroCta: 'Shop Tech',
      heroBg: 'https://picsum.photos/seed/tech-hero/1600/900',
      catTitle: 'Browse Categories',
      cat1Name: 'Smart Home', cat2Name: 'Wearables', cat3Name: 'Audio',
      topSellTitle: 'Top Picks',
      prod1Name: 'Pro Headphones', prod1Price: '$299',
      prod2Name: 'Smart Watch', prod2Price: '$449',
      prod3Name: 'Mesh Speaker', prod3Price: '$129',
      prod4Name: 'USB-C Hub', prod4Price: '$79',
      promoTitle: 'Tech Sale Event',
      promoCta: 'Claim Deal',
      newsTitle: 'Stay Connected',
      footerDesc: 'Bringing tomorrow\'s tech to your door.',
    },
    description: 'Dark, sleek interface optimised for showcasing electronics and digital products.',
    tags: ['Dark', 'Sleek', 'Technical'],
    popular: false,
    isNew: true,
    featured: false,
  },

  // ─── 6. Cozy Home ────────────────────────────────────────────────────────
  {
    id: 'tmpl_cozy_home',
    name: 'Cozy Home',
    category: 'Home & Living',
    primaryColor: '#FF7043',
    accentColor: '#FFF3EF',
    defaultFont: "'Outfit', sans-serif",
    heroLayout: 'centered',
    layoutStyle: 'masonry',
    borderRadius: 'large',
    colorSchemes: [...DEFAULT_COLOR_SCHEMES],
    fontOptions: [...DEFAULT_FONT_OPTIONS],
    defaultContent: {
      ...BASE_DEFAULT_CONTENT,
      storeName: 'HAVEN',
      heroTitle: 'Make Your House a Home.',
      heroSubtitle: 'Warm, curated pieces that bring comfort and character to every room.',
      heroCta: 'Discover Comfort',
      heroBg: 'https://picsum.photos/seed/cozy-hero/1600/900',
      catTitle: 'Shop by Room',
      cat1Name: 'Living Room', cat2Name: 'Bedroom', cat3Name: 'Kitchen',
      topSellTitle: 'Customer Favourites',
      prod1Name: 'Knit Throw', prod1Price: '$79',
      prod2Name: 'Candle Set', prod2Price: '$38',
      prod3Name: 'Woven Basket', prod3Price: '$55',
      prod4Name: 'Linen Pillow', prod4Price: '$45',
      promoTitle: 'Autumn Collection',
      promoCta: 'Shop Warmth',
      newsTitle: 'Home Inspo & Deals',
      footerDesc: 'Handpicked for homes that breathe.',
    },
    description: 'Warm tones, soft textures and inviting layouts. Built for home decor and lifestyle brands.',
    tags: ['Warm', 'Cozy', 'Lifestyle'],
    popular: false,
    isNew: false,
    featured: false,
  },

  // ─── 7. Beauty Glow ──────────────────────────────────────────────────────
  {
    id: 'tmpl_beauty_glow',
    name: 'Beauty Glow',
    category: 'Beauty',
    primaryColor: '#EC4899',
    accentColor: '#FDF2F8',
    defaultFont: "'Playfair Display', serif",
    heroLayout: 'centered',
    layoutStyle: 'grid',
    borderRadius: 'large',
    colorSchemes: [...DEFAULT_COLOR_SCHEMES],
    fontOptions: [...DEFAULT_FONT_OPTIONS],
    defaultContent: {
      ...BASE_DEFAULT_CONTENT,
      storeName: 'GLŌW',
      heroTitle: 'Radiance, Redefined.',
      heroSubtitle: 'Luxury skincare and cosmetics formulated for every shade and skin type.',
      heroCta: 'Find Your Glow',
      heroBg: 'https://picsum.photos/seed/beauty-hero/1600/900',
      catTitle: 'Shop by Concern',
      cat1Name: 'Skincare', cat2Name: 'Makeup', cat3Name: 'Fragrance',
      topSellTitle: 'Holy Grails',
      prod1Name: 'Vitamin C Serum', prod1Price: '$68',
      prod2Name: 'Rose Lip Gloss', prod2Price: '$22',
      prod3Name: 'Night Cream', prod3Price: '$89',
      prod4Name: 'Glow Mist', prod4Price: '$34',
      promoTitle: 'Glow Up Sale',
      promoCta: 'Shop Glow',
      newsTitle: 'Beauty Secrets Await',
      footerDesc: 'Luxury beauty, accessible to all.',
    },
    description: 'Luxurious gradients and elegant typography designed for cosmetics and skincare brands.',
    tags: ['Elegant', 'Luxury', 'Feminine'],
    popular: true,
    isNew: false,
    featured: true,
  },

  // ─── 8. Green Earth ──────────────────────────────────────────────────────
  {
    id: 'tmpl_green_earth',
    name: 'Green Earth',
    category: 'Home & Living',
    primaryColor: '#00C48C',
    accentColor: '#E6FAF5',
    defaultFont: "'Outfit', sans-serif",
    heroLayout: 'split',
    layoutStyle: 'list',
    borderRadius: 'large',
    colorSchemes: [...DEFAULT_COLOR_SCHEMES],
    fontOptions: [...DEFAULT_FONT_OPTIONS],
    defaultContent: {
      ...BASE_DEFAULT_CONTENT,
      storeName: 'TERRA',
      heroTitle: 'Good for You. Good for Earth.',
      heroSubtitle: 'Sustainable, ethical products crafted with the planet in mind.',
      heroCta: 'Shop Sustainably',
      heroBg: 'https://picsum.photos/seed/green-hero/1600/900',
      catTitle: 'Eco Collections',
      cat1Name: 'Zero Waste', cat2Name: 'Organic Textiles', cat3Name: 'Natural Beauty',
      topSellTitle: 'Earth Approved',
      prod1Name: 'Bamboo Tumblers', prod1Price: '$29',
      prod2Name: 'Beeswax Wraps', prod2Price: '$18',
      prod3Name: 'Organic Cotton Tote', prod3Price: '$25',
      prod4Name: 'Reef-Safe Sunscreen', prod4Price: '$22',
      promoTitle: 'Earth Day Essentials',
      promoCta: 'Shop Green',
      newsTitle: 'Join the Movement',
      footerDesc: 'Sustainable living starts here.',
    },
    description: 'Nature-inspired design with organic shapes and earthy palettes. Ideal for eco-friendly brands.',
    tags: ['Eco', 'Natural', 'Minimal'],
    popular: false,
    isNew: true,
    featured: false,
  },

  // ─── 9. Sport Pro ────────────────────────────────────────────────────────
  {
    id: 'tmpl_sport_pro',
    name: 'Sport Pro',
    category: 'Sports',
    primaryColor: '#FACC15',
    accentColor: '#111827',
    defaultFont: "'Inter', sans-serif",
    heroLayout: 'fullwidth',
    layoutStyle: 'grid',
    borderRadius: 'none',
    colorSchemes: [...DEFAULT_COLOR_SCHEMES],
    fontOptions: [...DEFAULT_FONT_OPTIONS],
    defaultContent: {
      ...BASE_DEFAULT_CONTENT,
      storeName: 'PRO GEAR',
      heroTitle: 'Built for Champions.',
      heroSubtitle: 'Professional-grade sports equipment and apparel for serious athletes.',
      heroCta: 'Shop Pro',
      heroBg: 'https://picsum.photos/seed/sport-hero/1600/900',
      catTitle: 'Pro Categories',
      cat1Name: 'Equipment', cat2Name: 'Apparel', cat3Name: 'Recovery',
      topSellTitle: 'Pro Picks',
      prod1Name: 'Carbon Cleats', prod1Price: '$219',
      prod2Name: 'Pro Shin Guards', prod2Price: '$55',
      prod3Name: 'Compression Sleeve', prod3Price: '$39',
      prod4Name: 'Recovery Roller', prod4Price: '$49',
      promoTitle: 'Championship Deals',
      promoCta: 'Shop Now',
      newsTitle: 'Train Smarter',
      footerDesc: 'Pro gear for every level of play.',
    },
    description: 'High-energy layouts with bold typography and dynamic grid systems for sports and activewear.',
    tags: ['Bold', 'Dynamic', 'Dark'],
    popular: false,
    isNew: true,
    featured: false,
  },

  // ─── 10. Artisan Craft ───────────────────────────────────────────────────
  {
    id: 'tmpl_artisan_craft',
    name: 'Artisan Craft',
    category: 'General',
    primaryColor: '#92400E',
    accentColor: '#FEF3C7',
    defaultFont: "'Playfair Display', serif",
    heroLayout: 'split',
    layoutStyle: 'masonry',
    borderRadius: 'small',
    colorSchemes: [...DEFAULT_COLOR_SCHEMES],
    fontOptions: [...DEFAULT_FONT_OPTIONS],
    defaultContent: {
      ...BASE_DEFAULT_CONTENT,
      storeName: 'ATELIER',
      heroTitle: 'Made with Heart.',
      heroSubtitle: 'Handcrafted goods by independent artisans from around the world.',
      heroCta: 'Explore Crafts',
      heroBg: 'https://picsum.photos/seed/artisan-hero/1600/900',
      catTitle: 'Craft Collections',
      cat1Name: 'Ceramics', cat2Name: 'Woodwork', cat3Name: 'Weaving',
      topSellTitle: 'Beloved Pieces',
      prod1Name: 'Hand-Thrown Bowl', prod1Price: '$78',
      prod2Name: 'Oak Serving Board', prod2Price: '$95',
      prod3Name: 'Macramé Wall Art', prod3Price: '$120',
      prod4Name: 'Beeswax Candle', prod4Price: '$32',
      promoTitle: 'Makers\' Market',
      promoCta: 'Shop Handmade',
      newsTitle: 'Stories from Our Makers',
      footerDesc: 'Celebrating craftsmanship and creativity.',
    },
    description: 'Handcrafted feel with warm typography and story-driven layouts. Perfect for artisans and makers.',
    tags: ['Artisan', 'Handcrafted', 'Story'],
    popular: true,
    isNew: false,
    featured: false,
  },
];

// Categories derived from templates (used in filter bar)
export const TEMPLATE_CATEGORIES = [
  'All',
  ...new Set(MOCK_TEMPLATES.map((t) => t.category)),
];

// Popular theme colors for the color swatch filter
export const THEME_COLORS = [
  { label: 'Purple',  hex: '#8B3DFF' },
  { label: 'Pink',    hex: '#FF6B9D' },
  { label: 'Blue',    hex: '#3B82F6' },
  { label: 'Green',   hex: '#00C48C' },
  { label: 'Coral',   hex: '#FF7043' },
  { label: 'Yellow',  hex: '#FACC15' },
  { label: 'Dark',    hex: '#1A1D23' },
  { label: 'Rose',    hex: '#EC4899' },
];

// Legacy export kept for backward compat — now delegates to InteractivePreview
export const generateTemplateHTML = (templateId, customizations) => {
  const tmpl = MOCK_TEMPLATES.find(t => t.id === templateId);
  return `<html><body style="display:flex;align-items:center;justify-content:center;height:100vh;font-family:sans-serif;background:#f8f8f8;"><p style="color:#888;">Loading preview…</p></body></html>`;
};
